services:
  postgres:
    image: postgres:18-alpine
    container_name: onepiecetcg-postgres
    environment:
      POSTGRES_DB: onepiecetcg
      POSTGRES_USER: onepiecetcg
      POSTGRES_PASSWORD: onepiecetcg
    ports:
      - '5432:5432'
    volumes:
      - postgres18-data:/var/lib/postgresql
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U onepiecetcg -d onepiecetcg']
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres18-data:
