apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: onepiecetcg-api-secrets
  namespace: onepiecetcg
spec:
  provider: gke
  parameters:
    secrets: |
      - resourceName: "projects/decouverte-gke/secrets/database-url/versions/latest"
        path: "database-url"
      - resourceName: "projects/decouverte-gke/secrets/better-auth-secret/versions/latest"
        path: "better-auth-secret"
      - resourceName: "projects/decouverte-gke/secrets/oauth-google-client-id/versions/latest"
        path: "oauth-google-client-id"
      - resourceName: "projects/decouverte-gke/secrets/oauth-google-client-secret/versions/latest"
        path: "oauth-google-client-secret"
