apiVersion: secret-sync.gke.io/v1
kind: SecretSync
metadata:
  name: api-secrets
  namespace: onepiecetcg
spec:
  serviceAccountName: onepiecetcg-api
  secretProviderClassName: onepiecetcg-api-secrets
  secretObject:
    type: Opaque
    data:
      - sourcePath: "database-url"
        targetKey: "DATABASE_URL"
      - sourcePath: "better-auth-secret"
        targetKey: "BETTER_AUTH_SECRET"
      - sourcePath: "oauth-google-client-id"
        targetKey: "GOOGLE_CLIENT_ID"
      - sourcePath: "oauth-google-client-secret"
        targetKey: "GOOGLE_CLIENT_SECRET"
